print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/natasjahelledie/Documents/Uddannelse/5. semester/P5/ProgrammingGame/LearningProgrammingGameUnity/Assets/Resources/GameObjects/pipes2.mb"`)
{		
	file -o "/Users/natasjahelledie/Documents/Uddannelse/5. semester/P5/ProgrammingGame/LearningProgrammingGameUnity/Assets/Resources/GameObjects/pipes2.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/natasjahelledie/Documents/Uddannelse/5. semester/P5/ProgrammingGame/LearningProgrammingGameUnity/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/natasjahelledie/Documents/Uddannelse/5. semester/P5/ProgrammingGame/LearningProgrammingGameUnity/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/natasjahelledie/Documents/Uddannelse/5. semester/P5/ProgrammingGame/LearningProgrammingGameUnity/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
